# setup.yml

- name: Setup adminer
  hosts: all

  roles:
   - role: geerlingguy.postgresql
     tags: postgresql
   - role: geerlingguy.apache
     tags: [ apache, web ]
   - role: geerlingguy.php
     tags: [ php, web ]
   - role: adminer
     tags: adminer
