# roles/adminer/tasks/main.yml

- name: Create Adminer directory
  file:
    path: '{{ adminer_directory }}'
    state: directory
  
- name: Download Adminer file
  get_url:
     url: '{{ adminer_download_url }}'
     dest: '{{ adminer_directory }}/index.php'
  

